### ISSUE TITLE
Cannot clone the repository: illegal path

### ISSUE THREAD

**Issue by j-magnolia** [gluon/AbletonLive10.1_MIDIRemoteScripts#2]
When I try to clone this repository under Windows, git can fetch the repository, but cannot check it out. I get the following error message:
```
error: invalid path 'ableton/v2/control_surface/control/elements/elements/*.py_failed'
```
Having a file in the repository with an asterisk in its name (`'*.py_failed'`) is a problem for git. This file has zero bytes, so I wonder, is it necessary to have an empty file with this problematic name in the repository, or could it be removed and added to .gitignore?

I am using `git version 2.27.0.windows.1`

**Comment by gluon** [comment]
there is no such file in the path, isn't there?

**Comment by j-magnolia** [comment]
There is such a file here: https://github.com/gluon/AbletonLive10.1_MIDIRemoteScripts/blob/master/ableton/v2/control_surface/control/elements/elements/*.py_failed

**Comment by gluon** [comment]
it was not in my own local folder (as I think wildecard is not allowed on any OS) and it was here on github. I removed it. let me know.

**Comment by j-magnolia** [comment]
Thanks. That fixed it.
